"""
TLV Type Definitions - Auto-generated from TLV_TypeDefs.json
This file is auto-generated - DO NOT EDIT MANUALLY
"""

# ============================================================================
# TLV Type Constants
# ============================================================================

SYS_HEARTBEAT = 1
SYS_STATE = 2
SYS_CMD = 3
SYS_INFO_REQ = 4
SYS_INFO_RSP = 5
SYS_CONFIG_REQ = 6
SYS_CONFIG_RSP = 7
SYS_CONFIG_SET = 8
SYS_POWER = 9
SYS_DIAG_REQ = 10
SYS_DIAG_RSP = 11
SYS_ODOM_RESET = 12
SYS_ODOM_PARAM_SET = 13
DC_ENABLE = 16
DC_SET_POSITION = 17
DC_SET_VELOCITY = 18
DC_SET_PWM = 19
DC_STATE_ALL = 20
DC_PID_REQ = 21
DC_PID_RSP = 22
DC_PID_SET = 23
DC_RESET_POSITION = 24
DC_HOME = 25
STEP_ENABLE = 32
STEP_MOVE = 33
STEP_HOME = 34
STEP_STATE_ALL = 35
STEP_CONFIG_REQ = 36
STEP_CONFIG_RSP = 37
STEP_CONFIG_SET = 38
SERVO_ENABLE = 48
SERVO_SET = 49
SERVO_STATE_ALL = 50
SENSOR_IMU = 64
SENSOR_KINEMATICS = 65
SENSOR_ULTRASONIC_ALL = 66
SENSOR_MAG_CAL_CMD = 67
SENSOR_MAG_CAL_STATUS = 68
IO_SET_LED = 80
IO_SET_NEOPIXEL = 81
IO_INPUT_STATE = 82
IO_OUTPUT_STATE = 83

# Dictionary for programmatic access
TLV_TYPES = {
    'SYS_HEARTBEAT': 1,
    'SYS_STATE': 2,
    'SYS_CMD': 3,
    'SYS_INFO_REQ': 4,
    'SYS_INFO_RSP': 5,
    'SYS_CONFIG_REQ': 6,
    'SYS_CONFIG_RSP': 7,
    'SYS_CONFIG_SET': 8,
    'SYS_POWER': 9,
    'SYS_DIAG_REQ': 10,
    'SYS_DIAG_RSP': 11,
    'SYS_ODOM_RESET': 12,
    'SYS_ODOM_PARAM_SET': 13,
    'DC_ENABLE': 16,
    'DC_SET_POSITION': 17,
    'DC_SET_VELOCITY': 18,
    'DC_SET_PWM': 19,
    'DC_STATE_ALL': 20,
    'DC_PID_REQ': 21,
    'DC_PID_RSP': 22,
    'DC_PID_SET': 23,
    'DC_RESET_POSITION': 24,
    'DC_HOME': 25,
    'STEP_ENABLE': 32,
    'STEP_MOVE': 33,
    'STEP_HOME': 34,
    'STEP_STATE_ALL': 35,
    'STEP_CONFIG_REQ': 36,
    'STEP_CONFIG_RSP': 37,
    'STEP_CONFIG_SET': 38,
    'SERVO_ENABLE': 48,
    'SERVO_SET': 49,
    'SERVO_STATE_ALL': 50,
    'SENSOR_IMU': 64,
    'SENSOR_KINEMATICS': 65,
    'SENSOR_ULTRASONIC_ALL': 66,
    'SENSOR_MAG_CAL_CMD': 67,
    'SENSOR_MAG_CAL_STATUS': 68,
    'IO_SET_LED': 80,
    'IO_SET_NEOPIXEL': 81,
    'IO_INPUT_STATE': 82,
    'IO_OUTPUT_STATE': 83,
}

# Reverse map: integer type id → name string
TLV_NAMES = {v: k for k, v in TLV_TYPES.items()}
